version: "3.5"
services:
  userauth:
    image:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - mongodb
    tty: true
    stdin_open: true
    restart: always
    command: /wait-for-it.sh -t 30 mongodb:27017 -- /app/bin/userauth
  mongodb:
    restart: always
    image: mongo:3.7
    environment:
      - MONGODB_DATABASE=user_auth
    ports:
      - "27017:27017"
    networks:
      - webnet
networks:
  webnet:
    name: webnet
